### PR TITLE
add support for external mongo list or alternate mongo server config …

### PR DESCRIPTION
**Pull request by yairogen**
…prefix

[Review on Reviewable](https://reviewable.io/reviews/foundation-runtime/cluster/8)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/foundation-runtime/cluster/pull/8" target="_blank">ReviewNinja

**Comment by igreenfield** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 27 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDfs6xatlLVBE1i-l-:-KBDfs6xatlLVBE1i-l0:1278999347) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L27)):*
Why not final?

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 53 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDg4u0EXgfpA9vt17_:-KBDg4u0EXgfpA9vt17a:-1124700368) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L53)):*
this. as all the other fields

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java, line 55 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDgdspfMFMn2d1mp4Z:-KBDgdspfMFMn2d1mp4_:-395788553) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java#L55)):*
.addAll 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foundation-runtime/cluster/8)*

**Comment by yairogen** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 27 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDfs6xatlLVBE1i-l-:-KBDjP0MVGD7c-eNKvg8:-497556202) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L27)):*
because we set it after job name injected in the constructor

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 53 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDg4u0EXgfpA9vt17_:-KBDjrqRk-yMOhiFyD0P:-1717262374) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L53)):*
comment not clear

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java, line 55 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDgdspfMFMn2d1mp4Z:-KBDjvbE-uFSe9romrfS:1843484896) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java#L55)):*
why is that better then replacing the entire list? replacing is more efficient

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foundation-runtime/cluster/8)*

**Comment by igreenfield** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 27 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDfs6xatlLVBE1i-l-:-KBDm_KzoiRmlmCVoN_6:-271930292) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L27)):*
constructor args could be final.
and same for jobName

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 53 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDg4u0EXgfpA9vt17_:-KBDlnVDLpWQfdoJtPHG:-1088632279) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L53)):*
this.mastershipElector

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java, line 55 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDgdspfMFMn2d1mp4Z:-KBDlwmgWpEqD4Kl5XqB:105219464) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java#L55)):*
this is list so if I pass it and change it before you read it...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foundation-runtime/cluster/8)*

**Comment by yairogen** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 27 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDfs6xatlLVBE1i-l-:-KBDnNKgYC7Y88Ja95bY:-499146009) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L27)):*
Done.

---

*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java, line 53 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDg4u0EXgfpA9vt17_:-KBDnSU7Q4eQ-GFHKrtk:-499146009) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/registry/MasterSlaveRunnable.java#L53)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foundation-runtime/cluster/8)*

**Comment by yairogen** [comment]
*[master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java, line 55 \[r2\]](https://reviewable.io:443/reviews/foundation-runtime/cluster/8#-KBDgdspfMFMn2d1mp4Z:-KBDnrVX8BVuEFZ_UYWF:-499146009) ([raw file](https://github.com/foundation-runtime/cluster/blob/2af2ae33ccb53111e39e1f5c8ef322da7df692b5/master-slave/src/main/java/com/cisco/oss/foundation/cluster/utils/MasterSlaveConfigurationUtil.java#L55)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foundation-runtime/cluster/8)*

**Comment by igreenfield** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foundation-runtime/cluster/8)*

**Pull request merged**
